#include"test.h"
#include"egg.h"

int strategy;

LISTNODEPTR headPtr;
DWORD WINAPI inputOder(LPVOID lpParameter)
{
	double X,Y;
	while(1)
	{
		while(!(WaitForEvent()==KEYDOWN)){}//当没有接收到任何事件的时候进入空循环
		
		//如果鼠标左键被按下，根据按下的位置，判断是屏幕上的什么位置被按下
		if(GetStruckKey()==VK_LBUTTON)
		{
			X=GetMouseX();
			Y=GetMouseY();
			
			if((X>130&&X<160)&&(Y>395&&Y<425))
			{
				if(Elevator.floor==9&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_down[9]=1;
					printf("%d\n",NoResponseFloor_down[9]);
					addition(29);
					SetActiveEgg(heggs[29]);
					ShowEgg(1);	
				}
				
			}
			if((X>110&&X<140)&&(Y>350&&Y<380))
			{
				if(Elevator.floor==8&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_up[8]=1;
					addition(18);
					SetActiveEgg(heggs[18]);
					ShowEgg(1);
				}
			}
			if((X>150&&X<180)&&(Y>350&&Y<380))
			{
				if(Elevator.floor==8&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_down[8]=1;
					addition(28);
					SetActiveEgg(heggs[28]);
					ShowEgg(1);
				}
			}
			if((X>110&&X<140)&&(Y>305&&Y<335))
			{
				if(Elevator.floor==7&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_up[7]=1;
					addition(17);
					SetActiveEgg(heggs[17]);
					ShowEgg(1);
				}
			}
			if((X>150&&X<180)&&(Y>305&&Y<335))
			{
				if(Elevator.floor==7&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_down[7]=1;
					addition(27);
					SetActiveEgg(heggs[27]);
					ShowEgg(1);
				}
			}
			if((X>110&&X<140)&&(Y>260&&Y<290))
			{
				if(Elevator.floor==6&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_up[6]=1;
					addition(16);
					SetActiveEgg(heggs[16]);
					ShowEgg(1);
				}
			}
			if((X>150&&X<180)&&(Y>260&Y<290))
			{
				if(Elevator.floor==6&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_down[6]=1;
					addition(26);
					SetActiveEgg(heggs[26]);
					ShowEgg(1);
				}
			}
			if((X>110&&X<140)&&(Y>215&&Y<245))
			{
				if(Elevator.floor==5&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_up[5]=1;
					addition(15);
					SetActiveEgg(heggs[15]);
					ShowEgg(1);
				}
			}
			if((X>150&&X<180)&&(Y>215&&Y<245))
			{
				if(Elevator.floor==5&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_down[5]=1;
					addition(25);
					SetActiveEgg(heggs[25]);
					ShowEgg(1);
				}
			}
			if((X>110&&X<140)&&(Y>170&&Y<200))
			{
				if(Elevator.floor==4&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_up[4]=1;
					addition(14);
					SetActiveEgg(heggs[14]);
					ShowEgg(1);
				}
			}
			if((X>150&&X<180)&&(Y>170&&Y<200))
			{
				if(Elevator.floor==4&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_down[4]=1;
					addition(24);
					SetActiveEgg(heggs[24]);
					ShowEgg(1);
				}
			}
			if((X>110&&X<140)&&(Y>125&&Y<155))
			{
				if(Elevator.floor==3&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_up[3]=1;
					addition(13);
					SetActiveEgg(heggs[13]);
					ShowEgg(1);
				}
			}
			if((X>150&&X<180)&&(Y>125&&Y<155))
			{
				if(Elevator.floor==3&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_down[3]=1;
					addition(23);
					SetActiveEgg(heggs[23]);
					ShowEgg(1);
				}
			}
			if((X>110&&X<140)&&(Y>80&&Y<110))
			{
				if(Elevator.floor==2&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_up[2]=1;
					addition(12);
					SetActiveEgg(heggs[12]);
					ShowEgg(1);
				}
			}
			if((X>150&&X<180)&&(Y>80&&Y<110))
			{
				if(Elevator.floor==2&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_down[2]=1;
					addition(22);
					SetActiveEgg(heggs[22]);
					ShowEgg(1);
				}
				
			}
			if((X>130&&X<160)&&(Y>35&&Y<65))
			{
				if(Elevator.floor==1&&Elevator.state==2)
					openDoor=1;
				else
				{
					NoResponseFloor_up[1]=1;
					addition(11);
					SetActiveEgg(heggs[11]);
					ShowEgg(1);
				}
			}
			if((X>570&&X<640)&&(Y>380&&Y<450))
			{
				strategy=1;
				SetActiveEgg(heggs[10]);
				ShowEgg(1);
				SetActiveEgg(heggs[19]);
				ShowEgg(0);
			}	
			if((X>680&&X<750)&&(Y>380&&Y<450))
			{
				strategy=2;
				SetActiveEgg(heggs[19]);
				ShowEgg(1);
				SetActiveEgg(heggs[10]);
				ShowEgg(0);
			}	
			if((X>560&&X<620)&&(Y>270&&Y<330))
			{
				if(InsideCmd[1]==1) 
				{
					if(fabs(1-Elevator.floor)>=1)//取消内部已有指令
					{
						InsideCmd[1]=0;
						cancelRequire(1);
						SetActiveEgg(heggs[1]);
						ShowEgg(0); 
					}	 
					else
						printf("Sorry,you could not cancel your request for your safety.\n");
				}
				else
				{
					if(Elevator.floor!=1)
						{
							InsideCmd[1]=1;
							addition(1);
							SetActiveEgg(heggs[1]);
							ShowEgg(1);
						}
					else
						printf("Sorry,the elevator is at the 1th floor,could not answer!\n");
				}
			}
			
			if((X>630&&X<690)&&(Y>270&&Y<330))
			{
				if(InsideCmd[2]==1) 
				{
					if(fabs(2-Elevator.floor)>=1)//取消内部已有指令
					{
						
						InsideCmd[2]=0;
						cancelRequire(2);
						SetActiveEgg(heggs[2]);
						ShowEgg(0); 
						
					}	 
					else
						printf("Sorry,you could not cancel your request for your safety.\n");
				}
				else
				{
					if(Elevator.floor!=2)
					{	
						SetActiveEgg(heggs[2]);
						ShowEgg(1);
						InsideCmd[2]=1;
						addition(2);
					
					}	
					else
						printf("Sorry,the elevator is at the 2th floor,could not answer!\n");
				}
			}
			
			if((X>700&&X<760)&&(Y>270&&Y<330))
			{
				if(InsideCmd[3]==1) 
				{
					if(fabs(3-Elevator.floor)>=1)//取消内部已有指令
					{
						InsideCmd[3]=0;
						cancelRequire(3); 
						SetActiveEgg(heggs[3]);
						ShowEgg(0);
					}	 
					else
						printf("Sorry,you could not cancel your request for your safety.\n");
				}
				else
				{
					if(Elevator.floor!=2)
					{
						InsideCmd[3]=1;
						addition(3);
						SetActiveEgg(heggs[3]);
						ShowEgg(1);
					}	
					else
						printf("Sorry,the elevator is at the 3th floor,could not answer!\n");
				}
			}
			
			if((X>560&&X<620)&&(Y>200&&Y<260))
			{
				if(InsideCmd[4]==1) 
				{
					if(fabs(4-Elevator.floor)>=1)//取消内部已有指令
					{
						InsideCmd[4]=0;
						cancelRequire(4); 
						SetActiveEgg(heggs[4]);
						ShowEgg(0);
					}	 
					else
						printf("Sorry,you could not cancel your request for your safety.\n");
				}
				else
				{
					if(Elevator.floor!=2)
					{
						InsideCmd[4]=1;
						addition(4);
						SetActiveEgg(heggs[4]);
						ShowEgg(1);
					}	
					else
						printf("Sorry,the elevator is at the 4th floor,could not answer!\n");
				}
			}
			if((X>630&&X<690)&&(Y>200&&Y<260))
			{
				if(InsideCmd[5]==1) 
				{
					if(fabs(5-Elevator.floor)>=1)//取消内部已有指令
					{
						InsideCmd[5]=0;
						cancelRequire(5); 
						SetActiveEgg(heggs[5]);
						ShowEgg(0);
					}	 
					else
						printf("Sorry,you could not cancel your request for your safety.\n");
				}
				else
				{
					if(Elevator.floor!=2)
					{
						InsideCmd[5]=1;
						addition(5);
						SetActiveEgg(heggs[5]);
						ShowEgg(1);
					}	
					else
						printf("Sorry,the elevator is at the 5th floor,could not answer!\n");
				}
			}
			if((X>700&&X<760)&&(Y>200&&Y<260))
			{
				if(InsideCmd[6]==1) 
				{
					if(fabs(6-Elevator.floor)>=1)//取消内部已有指令
					{
						InsideCmd[6]=0;
						cancelRequire(6);
						SetActiveEgg(heggs[6]);
						ShowEgg(0);
					}	 
					else
						printf("Sorry,you could not cancel your request for your safety.\n");
				}
				else
				{
					if(Elevator.floor!=2)
					{
						InsideCmd[6]=1;
						addition(6);
						SetActiveEgg(heggs[6]);
						ShowEgg(1);
					}	
					else
						printf("Sorry,the elevator is at the 6th floor,could not answer!\n");
				}
			}
			if((X>560&&X<620)&&(Y>130&&Y<190))
			{
				if(InsideCmd[7]==1) 
				{
					if(fabs(7-Elevator.floor)>=1)//取消内部已有指令
					{
						InsideCmd[7]=0;
						cancelRequire(7); 
						SetActiveEgg(heggs[7]);
						ShowEgg(0);
					}	 
					else
						printf("Sorry,you could not cancel your request for your safety.\n");
				}
				else
				{
					if(Elevator.floor!=2)
					{
						InsideCmd[7]=1;
						addition(7);
						SetActiveEgg(heggs[7]);
						ShowEgg(1);
					}	
					else
						printf("Sorry,the elevator is at the 7th floor,could not answer!\n");
				}
			}
			if((X>630&&X<690)&&(Y>130&&Y<190))
			{
				if(InsideCmd[8]==1) 
				{
					if(fabs(8-Elevator.floor)>=1)//取消内部已有指令
					{
						InsideCmd[8]=0;
						cancelRequire(8); 
						SetActiveEgg(heggs[8]);
						ShowEgg(0);
					}	 
					else
						printf("Sorry,you could not cancel your request for your safety.\n");
				}
				else
				{
					if(Elevator.floor!=2)
					{
						InsideCmd[8]=1;
						addition(8);
						SetActiveEgg(heggs[8]);
						ShowEgg(1);
					}	
					else
						printf("Sorry,the elevator is at the 8th floor,could not answer!\n");
				}
			}
			if((X>700&&X<760)&&(Y>130&&Y<190))
			{
				if(InsideCmd[9]==1) 
				{
					if(fabs(9-Elevator.floor)>=1)//取消内部已有指令
					{
						InsideCmd[9]=0;
						cancelRequire(9); 
						SetActiveEgg(heggs[9]);
						ShowEgg(0);
					}	 
					else
						printf("Sorry,you could not cancel your request for your safety.\n");
				}
				else
				{
					if(Elevator.floor!=2)
					{
						InsideCmd[9]=1;
						addition(9);
						SetActiveEgg(heggs[9]);
						ShowEgg(1);
					}	
					else
						printf("Sorry,the elevator is at the 9th floor,could not answer!\n");
				}
			}
			if((X>570&&X<645)&&(Y>30&&Y<105))
			{
				openDoor=1;
				SetActiveEgg(heggs[20]);
				ShowEgg(1);
				SetActiveEgg(heggs[21]);
				ShowEgg(0);
			}	
			if((X>675&&X<750)&&(Y>30&&Y<105))
			{
				closeDoor=1;
				SetActiveEgg(heggs[21]);
				ShowEgg(1);
				SetActiveEgg(heggs[20]);
				ShowEgg(0);
			}	
		}
//		Sleep(500); 
		
	}
	
}
